name: split-pro-dev

services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${POSTGRES_CONTAINER_NAME:-splitpro-db}
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-splitpro}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
      - POSTGRES_DB=${POSTGRES_DB:-splitpro}
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
    volumes:
      - database:/var/lib/postgresql/data
    ports:
      - '${POSTGRES_PORT:-5432}:${POSTGRES_PORT:-5432}'
    command: >
      postgres
      -c shared_preload_libraries=pg_cron
      -c cron.database_name=${POSTGRES_DB:-splitpro}

  minio:
    image: minio/minio
    container_name: splitpro-storage-dev
    ports:
      - 9002:9002
      - 9001:9001
    volumes:
      - minio:/data
    environment:
      MINIO_ROOT_USER: splitpro
      MINIO_ROOT_PASSWORD: password
    entrypoint: sh
    command: -c 'mkdir -p /data/splitpro && minio server /data --console-address ":9001" --address ":9002"'

volumes:
  database:
  minio:
